name: began-gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - namaster
  - pyyaml
  - numba
  - scikit-image
  - toml
  - healpy
  - tqdm
  - click
  - matplotlib
  - seaborn
  - tensorflow-gpu
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - optuna
     - tensorflow_probability
     - tables
     - dvc[gdrive]
     - camb
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
